// Generated by CoffeeScript 1.9.0
(function() {
  var child_process, log, lsCommand;

  log = loglevel.createLogger('ls', 'debug');

  child_process = Npm.require('child_process');

  lsCommand = function(options, done) {
    var ls;
    log.debug('spawning ls');
    ls = child_process.spawn("ls");
    log.debug('ls spawned');
    ls.stdout.setEncoding("utf8");
    ls.stdout.on("data", function(data) {
      return process.stdout.write(data);
    });
    ls.stderr.setEncoding("utf8");
    ls.stderr.on("data", function(data) {
      return process.stderr.write(data);
    });
    return ls.on("close", function(code, signal) {
      log.debug('ls closed');
      return done();
    });
  };

  CLI.registerCommand('ls', lsCommand, {}, true);

}).call(this);

//# sourceMappingURL=lscommand.js.map
