// Generated by CoffeeScript 1.9.0
(function() {
  CLI.registerCommand('member-join', function(options) {
    console.error("Hello world from practicalmeteor:mcli! error");
    return console.info("Hello world from practicalmeteor:mcli! info");
  });

}).call(this);

//# sourceMappingURL=member-join.js.map
